name: "go_web_bbs"
mode: "dev"
port: 8081
version: "0.0.1"
start_time: "2020-07-01"
machine_id: 1

auth:
  jwt_expire: 8760
log:
  level: "debug"
  filename: "go_web_bbs.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "go_web_bbs"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100